---
- name: Install firewalld
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm firewalld nftables
        firewall-offline-cmd --remove-service=ssh
        firewall-offline-cmd --zone public --add-rich-rule 'rule service name="ssh" accept limit value="2/m"'
        firewall-offline-cmd --zone=public --add-service=http
        firewall-offline-cmd --zone=public --add-service=https
        firewall-offline-cmd --zone=internal --add-service=http
        firewall-offline-cmd --zone=internal --add-service=https
        # Enable wireguard
        firewall-offline-cmd --zone=internal --add-service=wireguard
        firewall-offline-cmd --zone=public --add-service=wireguard
        # firewall-offline-cmd --zone=public --add-port=51820/udp
        # firewall-offline-cmd --zone=public --add-masquerade

        # Required to act as VPN
        firewall-offline-cmd --zone=public --add-interface=eth0
        firewall-offline-cmd --zone=internal --add-interface=wg0

        # Enable firewalld in cloud-init: systemctl enable firewalld
        systemctl disable firewalld

- name: enable logdenied=all
  ansible.builtin.lineinfile:
    path: /mnt/etc/firewalld/firewalld.conf
    regexp: ^\#*LogDenied=(.*)$
    line: LogDenied=all

- name: Install and enable tinyproxy
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm tinyproxy
        systemctl enable tinyproxy

- name: set tinyproxy.conf
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/tinyproxy/tinyproxy.conf
    content: |
      User tinyproxy
      Group tinyproxy
      Port 8888
      Listen 127.0.0.1
      Timeout 600
      DefaultErrorFile "/usr/share/tinyproxy/default.html"
      StatFile "/usr/share/tinyproxy/stats.html"
      Syslog On
      LogLevel Notice
      PidFile "/run/tinyproxy/tinyproxy.pid"
      MaxClients 100
      Allow 127.0.0.1
      Allow ::1
      ViaProxyName "tinyproxy"
      #Filter "/etc/tinyproxy/filter"
      #FilterType fnmatch
      #FilterCaseSensitive On
      #FilterDefaultDeny Yes

- name: set tinyproxy.conf filterlist
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/tinyproxy/filter
    content: |
      ## Switzerland
      pkg.adfinis.com
      mirror.init7.net
      mirror.metanet.ch
      mirror.puzzle.ch
      theswissbay.ch
      mirror.ungleich.ch
      mirror.worldhotspot.org

      ## Germany
      mirror.23m.com
      ftp.agdsn.de
      appuals.com
      mirror.bethselamin.de
      mirror.chaoticum.net
      mirror.checkdomain.de
      mirror.clientvps.com
      mirror.cmt.de
      os.codefionn.eu
      mirror.dogado.de
      mirror.f4st.host
      ftp.fau.de
      pkg.fef.moe
      dist-mirror.fem.tu-ilmenau.de
      mirror.fsrv.services
      mirror.gnomus.de
      archlinux.homeinfo.de
      mirror.informatik.tu-freiberg.de
      mirror.iusearchbtw.nl
      mirrors.janbruckner.de
      arch.jensgutermuth.de
      de.arch.mirror.kescher.at
      mirror.kumi.systems
      mirror.fra10.de.leaseweb.net
      mirror.metalgamer.eu
      mirror.mikrogravitation.org
      mirror.moson.org
      mirrors.n-ix.net
      mirror.netcologne.de
      mirrors.niyawe.de
      mirror.orbit-os.com
      packages.oth-regensburg.de
      mirror.pagenotfound.de
      phinau.de
      mirror.pseudoform.org
      www.ratenzahlung.de
      ftp.halifax.rwth-aachen.de
      mirror.satis-faction.de
      mirror.selfnet.de
      mirror.spaceint.fr
      ftp.spline.inf.fu-berlin.de
      mirror.sunred.org
      archlinux.thaller.ws
      mirror.ubrco.de
      mirror.undisclose.de
      arch.unixpeople.org
      ftp.wrz.de/pub
      mirror.wtnet.de
      mirrors.xtom.de
      arch.mirror.zachlge.org

- name: Create tinyproxy systemd drop-in directory
  ansible.builtin.file:
    path: /mnt/usr/lib/systemd/system/tinyproxy.service.d
    state: directory

- name: harden tinyproxy systemd service (common)
  copy:
    owner: root
    group: root
    force: yes
    src: "{{ playbook_dir }}/files/systemd-hardening-common.conf"
    dest: /mnt/usr/lib/systemd/system/tinyproxy.service.d/00-hardening-common.conf

- name: set firewall rules so that only tinyproxy and systemd-resolved are allowed to make calls to the internet
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 0 -o eth0 -m state --state ESTABLISHED,RELATED -j ACCEPT
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 1 -p tcp -m owner --uid-owner tinyproxy --dport 80 -j ACCEPT
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 1 -p tcp -m owner --uid-owner tinyproxy --dport 443 -j ACCEPT
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 1 -p tcp -m owner --uid-owner systemd-resolve -j ACCEPT
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 1 -p udp -m owner --uid-owner systemd-timesync -j ACCEPT
        # Azure Metadata Service
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 1 -p tcp -m tcp -d 169.254.169.254 --dport=80 -j ACCEPT
        # WireServer
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 1 -p tcp -m tcp -d 168.63.129.16 --dport=80 -j ACCEPT
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 1 -p tcp -m tcp -d 168.63.129.16 --dport=32526 -j ACCEPT
        # SMTP
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 1 -p tcp -m tcp --dport=587 -j ACCEPT
        # DNS over TLS
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 1 -p tcp -m tcp -d 9.9.9.9 --dport=853 -j ACCEPT
        # Drop all other outgoing traffic
        firewall-offline-cmd --direct --add-rule ipv4 filter OUTPUT 2 -o eth0 -j DROP

- name: Add http_proxy to environment
  ansible.builtin.lineinfile:
    path: /mnt/etc/environment
    line: http_proxy=http://127.0.0.1:8888
    create: yes

- name: Add HTTP_PROXY to environment
  ansible.builtin.lineinfile:
    path: /mnt/etc/environment
    line: HTTP_PROXY=http://127.0.0.1:8888
    create: yes

- name: Add https_proxy to environment
  ansible.builtin.lineinfile:
    path: /mnt/etc/environment
    line: https_proxy=http://127.0.0.1:8888
    create: yes

- name: Add HTTPS_PROXY to environment
  ansible.builtin.lineinfile:
    path: /mnt/etc/environment
    line: HTTPS_PROXY=http://127.0.0.1:8888
    create: yes

- name: Add no_proxy to environment
  ansible.builtin.lineinfile:
    path: /mnt/etc/environment
    line: no_proxy=localhost,127.0.0.1
    create: yes

- name: Add NO_PROXY to environment
  ansible.builtin.lineinfile:
    path: /mnt/etc/environment
    line: NO_PROXY=localhost,127.0.0.1
    create: yes

- name: Create systemd proxy env file
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/systemd/system/proxy.env
    content: |
      http_proxy=http://127.0.0.1:8888
      https_proxy=http://127.0.0.1:8888
      HTTP_PROXY=http://127.0.0.1:8888
      HTTPS_PROXY=http://127.0.0.1:8888
      no_proxy=localhost,127.0.0.1
      NO_PROXY=localhost,127.0.0.1
